# Generated by Django 2.0.6 on 2020-01-03 14:26

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('StudentDashBoard', '0002_auto_20191231_1855'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classTitle', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='LessonModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lessonName', models.CharField(max_length=2000)),
                ('possiblePoint', models.PositiveSmallIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('isProject', models.BooleanField(default=False)),
                ('rubricForProject', models.CharField(blank=True, max_length=2000, null=True)),
                ('cohort', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='StudentDashBoard.ClassModel')),
            ],
        ),
        migrations.RemoveField(
            model_name='classworkmodel',
            name='classworkName',
        ),
        migrations.RemoveField(
            model_name='classworkmodel',
            name='isProject',
        ),
        migrations.RemoveField(
            model_name='classworkmodel',
            name='possiblePoint',
        ),
        migrations.RemoveField(
            model_name='classworkmodel',
            name='rubricForProject',
        ),
        migrations.AlterField(
            model_name='attendacemodels',
            name='dateTimeRecord',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 3, 14, 26, 55, 836293, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='classworkmodel',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='StudentDashBoard.LessonModel'),
        ),
    ]
