# Generated by Django 2.0.6 on 2020-01-03 19:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('StudentDashBoard', '0005_auto_20200103_1431'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lessonmodel',
            name='rubricForProject',
        ),
        migrations.AddField(
            model_name='classworkmodel',
            name='rubricForProject',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='attendacemodels',
            name='dateTimeRecord',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 3, 19, 38, 52, 586501, tzinfo=utc)),
        ),
    ]
