# Generated by Django 2.0.6 on 2019-12-31 17:55

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendaceModels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateTimeRecord', models.DateTimeField(default=datetime.datetime(2019, 12, 31, 17, 55, 54, 990237, tzinfo=utc))),
            ],
        ),
        migrations.CreateModel(
            name='ClassWorkModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classworkName', models.CharField(max_length=500)),
                ('repo', models.CharField(max_length=2000)),
                ('possiblePoint', models.PositiveSmallIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('grade', models.PositiveSmallIntegerField()),
                ('isProject', models.BooleanField(default=False)),
                ('rubricForProject', models.CharField(blank=True, max_length=2000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ScoreCardModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentName', models.CharField(max_length=1000)),
                ('student', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='classworkmodel',
            name='scorecard',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='StudentDashBoard.ScoreCardModel'),
        ),
        migrations.AddField(
            model_name='attendacemodels',
            name='scorecard',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='StudentDashBoard.ScoreCardModel'),
        ),
    ]
