# Generated by Django 2.0.6 on 2019-12-31 18:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('StudentDashBoard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendacemodels',
            name='dateTimeRecord',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 31, 18, 55, 9, 449456, tzinfo=utc)),
        ),
    ]
