# Generated by Django 2.0.6 on 2020-01-03 14:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('StudentDashBoard', '0003_auto_20200103_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonmodel',
            name='sourceURL',
            field=models.CharField(default='test', max_length=3000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='attendacemodels',
            name='dateTimeRecord',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 3, 14, 29, 28, 923365, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='classworkmodel',
            name='repo',
            field=models.CharField(max_length=3000),
        ),
    ]
