# Generated by Django 2.0.6 on 2020-01-28 15:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('StudentDashBoard', '0007_auto_20200103_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendacemodels',
            name='dateTimeRecord',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 28, 15, 23, 20, 216166, tzinfo=utc)),
        ),
    ]
