# Generated by Django 2.0.6 on 2020-01-28 16:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('StudentDashBoard', '0008_auto_20200128_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendacemodels',
            name='dateTimeRecord',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 28, 16, 23, 18, 238924, tzinfo=utc)),
        ),
    ]
